operations:

    oro_order_payment_transaction_capture:
        preactions:
            - '@call_service_method':
                service: oro_apruve.method.apruve.provider
                method: hasPaymentMethod
                method_parameters: [$.data.paymentMethod]
                attribute: $.isApruve
        preconditions:
            '@and':
                - '@equal': [$.isApruve, false]

    oro_apruve_payment_transaction_invoice:
        extends: oro_order_payment_transaction_capture
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preconditions
            - actions
        label: oro.apruve.payment_transaction.invoice.label
        button_options:
            icon: fa-file-text-o
        preactions:
            - '@assign_constant_value':
                attribute: $.invoiceTransactionAction
                value: Oro\Bundle\ApruveBundle\Method\ApruvePaymentMethod::INVOICE
            - '@assign_constant_value':
                attribute: $.shipmentTransactionAction
                value: Oro\Bundle\ApruveBundle\Method\ApruvePaymentMethod::SHIPMENT
            - '@foreach':
                array: $.data.relatedPaymentTransactions
                value: $.relatedInvoiceTransaction
                actions:
                    - '@foreach':
                        conditions:
                            '@and':
                                - '@equal': [$.invoiceTransactionAction, $.relatedInvoiceTransaction.action]
                                - '@equal': [true, $.relatedInvoiceTransaction.successful]
                        parameters:
                            array: $.relatedInvoiceTransaction.relatedPaymentTransactions
                            value: $.relatedShipmentTransaction
                            actions:
                                - '@assign_value':
                                    conditions:
                                        '@and':
                                            - '@equal': [$.shipmentTransactionAction, $.relatedShipmentTransaction.action]
                                            - '@equal': [true, $.relatedShipmentTransaction.successful]
                                    parameters: [$.shipmentTransactionSuccessful, true]
        preconditions:
            '@and':
                - '@acl_granted': ['CHARGE_AUTHORIZED_PAYMENTS', $.entity]
                - '@equal': [$.data.entity_class, 'Oro\Bundle\OrderBundle\Entity\Order']
                - '@equal': [$.data.action, 'authorize']
                - '@not':
                    - '@payment_transaction_was_charged':
                        transaction: $.data
                - '@equal': [$.isApruve, true]
                - '@not_equal': [$.shipmentTransactionSuccessful, true]
        actions:
            - '@oro_apruve_payment_transaction_invoice':
                paymentTransaction: $.data
                transactionOptions: []
                attribute: $.result
            - '@flash_message':
                conditions:
                    '@equal': ['$.result[successful]', true]
                message: oro.apruve.payment_transaction.invoice.result.success
                type: 'success'
            - '@flash_message':
                conditions:
                    '@equal': ['$.result[successful]', false]
                message: '$.result[message]'
                type: 'error'
